### ISSUE TITLE
Incorrect implementation?

### ISSUE THREAD

**Issue by tweeter0830** [ml-research/semantic-image-editing#1]
I have been playing around with this example and I have found something unexpected. I think that the scaling logic never does anything and the thresholding logic does nothing in the provided example.

Take a look at this code:
```
scale = torch.clamp(
    (1 / torch.abs((noise_pred_text - noise_pred_edit_concept)))
    * edit_guidance_scale_c,
    max=1.0,
)
```

In my experiments (including reproducing the colab results), each element of `noise_pred_text - noise_pred_edit_concept` is always less than one. So, `1 / torch.abs((noise_pred_text - noise_pred_edit_concept)` is always > 1. Which means that edit_guidance_scale_c affects nothing and `scale` is always just a matrix of ones.

These ones are then applied to the following step:
```
edit_concept_scale = torch.where(
    (noise_pred_text - noise_pred_edit_concept)
    <= edit_threshold_c,
    torch.zeros_like(scale),
    scale,
)
```

Which means the result is always a matrix where each element is either a zero or a one. Additionally, this conditional is almost always met. So, edit_concept_scale is mostly (99% in most cases) an array of ones.

To confirm this, I took the colab example and set the edit_guidance_scale values to 0.001 and 1000000 and the results did not change at all. Changing the edit _threshold to [-0.9, -0.9, -0.9] also resulted in the same generated images. However, changing the edit _threshold to [-0.01, -0.01, -0.01] did change the results.

So, the conclusion I come to from this is that edit_guidance_scale does nothing at any value > 1 and in the example shown, the thresholding seems to be having no effect. The latter is just a consequence of this given example I guess.

Is this the intent of the algorithm? or is the implementation off?

**Comment by manuelbrack** [comment]
Hi there, 

You are absolutely right about your observations. We observed the same flaws in the implementation and fixed them with the latest commits.
Feel free to check out respective paper as well: https://arxiv.org/abs/2301.12247

**Comment by manuelbrack** [comment]
We also added some additional examples in Jupiter to try out the improved interface.
