### ISSUE TITLE
huggingface spaces demo

### ISSUE THREAD

**Issue by kno10** [ml-research/semantic-image-editing#2]
It would be great to have a huggingface space that demonstrates this.
Maybe you can have it sponsored to run on some GPU.
If I have to show someone the capabilities of stable diffusion, I usually rather go to https://huggingface.co/spaces/stabilityai/stable-diffusion instead of spinning up a colab (but that one appears to run on a quite powerful custom container).
For many current models, huggingface is a go to place to try them out on a sample.

**Comment by kno10** [comment]
See, e.g., the alternate approach of https://huggingface.co/spaces/xdecoder/Instruct-X-Decoder

**Comment by manuelbrack** [comment]
Yes definitely, we are already working with the huggingface team to create a demo :D

**Comment by manuelbrack** [comment]
Happy to say that we now have demo running on 🤗huggingface.
https://huggingface.co/spaces/AIML-TUDA/semantic-diffusion
